image: Visual Studio 2015

environment:
  global:
    GITHUB_USER_PASSWORD:
      secure: 6WYdvdZBuYIvf7m0zZuYuQG6G9AxpD88FeiWnYWoehYGXFAwK/y2eZMr27/sU/9R

  matrix:

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      TOOLCHAIN: "vs-15-2017"
      CONFIG: Release
      BUILD_SHARED: ON

    - TOOLCHAIN: "vs-14-2015-sdk-8-1"
      CONFIG: Release
      BUILD_SHARED: OFF

    - TOOLCHAIN: "vs-14-2015-win64-sdk-8-1"
      CONFIG: Release
      BUILD_SHARED: OFF      

    - TOOLCHAIN: "vs-14-2015-win64-sdk-8-1"
      CONFIG: Debug
      BUILD_SHARED: OFF

install:
  - cmd: bin\hunter_env.cmd

build_script:
  - cmd: set APPVEYOR_CMAKE_ARGS=ACF_HAS_GPU=OFF
  - cmd: bin\build-appveyor.cmd "%CONFIG%" "%TOOLCHAIN%" "%BUILD_SHARED%"

artifacts:
  - path: _archives\acf-*.tar.gz
    name: Releases

deploy:
  provider: GitHub
  auth_token:
    secure: "x43zgAFmaHoqWwNDZEVzMvEWQSkHojfRWnVGMnmQziw9ozwrJTEnZdz5QD39bXMv"
  artifact: /acf-.*\.tar.gz/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

branches:
  except:
    - /^pr\..*/
