set(EIGEN_CMAKE_ARGS
  BUILD_TESTING=OFF
  HUNTER_INSTALL_LICENSE_FILES=COPYING.MPL2
  CMAKE_Fortran_COMPILER=OFF
)

hunter_config(Eigen VERSION ${HUNTER_Eigen_VERSION} CMAKE_ARGS ${EIGEN_CMAKE_ARGS})
